import os
import google.generativeai as genai
from dotenv import load_dotenv
import re

load_dotenv()
API_KEY = os.environ.get("GEMINI_API_KEY")
if API_KEY:
    genai.configure(api_key=API_KEY)

def generate_sql_with_gemini(nl_query, schema):
    if not API_KEY:
        return {"ok": False, "error": "GEMINI_API_KEY is not set in .env"}

    # Format the schema for the prompt
    schema_str = "Database Schema:\n"
    for table, details in schema.items():
        schema_str += f"- Table: {table}\n"
        schema_str += f"  - Columns: {', '.join(details['columns'])}\n"

    prompt = f"""
    You are an expert SQL Data Analyst. Your job is to convert the following natural language query into a valid SQL query (specifically SQLite dialect) based ONLY on the provided schema.
    
    Rules:
    1. If the user asks for calculations (e.g. calculating totals, averages), use standard SQL math operations (e.g. SUM(), AVG(), or column1 + column2).
    2. Respond ONLY with the raw SQL query. 
    3. Do not include markdown formatting like ```sql or any explanations. Just the SQL string.
    4. Make sure to use the exact table names and column names as provided in the schema.
    5. IMPORTANT: If the user query asks for data or columns that are completely unrelated to the provided schema (e.g. asking for 'marks' when the table only has 'salary'), return exactly the string 'NOT_APPLICABLE' instead of generating a forced query.
    
    {schema_str}
    
    User Query: {nl_query}
    """
    
    try:
        model = genai.GenerativeModel('gemini-1.5-pro')
        response = model.generate_content(prompt)
        sql = response.text.strip()
        
        # Remove markdown if it accidentally included it
        if sql.startswith("```sql"):
            sql = sql[6:]
        if sql.startswith("```"):
            sql = sql[3:]
        if sql.endswith("```"):
            sql = sql[:-3]
            
        sql = sql.strip()
        return {"ok": True, "sql": sql, "explanation": "Generated by Gemini 1.5 Pro AI", "source": "gemini_ai"}
    except Exception as e:
        return {"ok": False, "error": str(e)}
